apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: {{ .Values.NameSpaceCluster }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine
        ports:
        - containerPort: 2049  # Puerto NFS
        volumeMounts:
        - name: nfs-storage
          mountPath: /nfsshare  # Ruta en el contenedor donde se expondrá el volumen compartido
        env:
        - name: SHARED_DIRECTORY
          value: /nfsshare  # Se asigna la ruta del volumen compartido como variable de entorno
        securityContext:
          privileged: true  # Necesario para que el contenedor tenga acceso a la red
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc  # Se refiere al PVC que proporcionará almacenamiento persistente
