apiVersion: v1
kind: Service
metadata:
  name: postfixadmin-service
  namespace: mail-srv
spec:
  selector:
    app: postfixadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
