apiVersion: v1
kind: Secret
metadata:
  name: postfixadmin-secrets
  namespace: mail-srv
type: Opaque
data:
  db_user: {{ .Values.db_username | b64enc }}  # Codificado en base64
  db_password: {{ .Values.db_password | b64enc }}  # Codificado en base64
