apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-mailbox-pvc
  namespace: {{ .Values.NamespaceCluster }} 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mailboxSize }} 
  storageClassName: manual
