---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postfix-dkim-socket-pv
  namespace: {{ .Values.NamespaceCluster }}
spec:
  capacity:
    storage: 200Mi  # Espacio solicitado para el socket
  accessModes:
    - ReadWriteOnce  # El volumen se monta como ReadWriteOnce
  storageClassName: manual  # Debe coincidir con el `storageClassName` del PersistentVolumeClaim
  volumeMode: Filesystem  # Volumen de tipo sistema de archivos
  nfs:
    path: /nfsshare  # Ruta compartida en el servidor NFS
    server: nfs-server.{{ .Values.NamespaceCluster }}.svc.cluster.local  # Nombre del servicio NFS en el clúster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postfix-dkim-socket-pvc  
  namespace: {{ .Values.NamespaceCluster }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi  # Espacio suficiente para el socket
  storageClassName: manual  # Debe coincidir con el `storageClassName` del PersistentVolume
