apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: {{ .Values.NameSpaceCluster }}
spec:
  capacity:
    storage: 10Gi  # Tamaño del almacenamiento
  accessModes:
    - ReadWriteMany  # Permite que varios pods escriban en el volumen
  persistentVolumeReclaimPolicy: Retain  # Política de retención para el volumen
  nfs:
    path: /nfsshare  # Ruta compartida en el servidor NFS
    server: nfs-server.mail-srv.svc.cluster.local
  storageClassName: standard  # Usar storageClassName común


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: mail-srv
spec:
  accessModes:
    - ReadWriteOnce  # O usa ReadWriteMany si lo necesitas
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage

