---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dovecot-mailbox
  namespace: {{ .Values.NamespaceCluster }}  # Corregido el uso de la variable para seguir la convención de nombres
spec:
  capacity:
    storage: 5Gi  # Tamaño del volumen
  accessModes:
    - ReadWriteMany  # Permite el acceso simultáneo de múltiples pods
  storageClassName: manual  # Clase de almacenamiento manual (puede ser modificada según el entorno)
  volumeMode: Filesystem  # Modo de volumen (Filesystem para la mayoría de los casos)
  nfs:
    path: /nfsshare  # Ruta compartida en el servidor NFS
    server: nfs-server.{{ .Values.NamespaceCluster }}.svc.cluster.local  # Nombre completo del servicio NFS en el clúster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-mailbox-pvc  
  namespace: {{ .Values.NamespaceCluster }} 
spec:
  accessModes:
    - ReadWriteMany  # El PVC tiene el mismo modo de acceso que el PV
  resources:
    requests:
      storage: 5Gi  # Espacio solicitado para el volumen
  storageClassName: manual  # Debe coincidir con el `storageClassName` del PersistentVolume
