apiVersion: v1
kind: Secret
metadata:
  name: postfix-secrets
  namespace: {{ .Values.NamespaceCluster }} 
type: Opaque
data:
  postfix_domain: {{ .Values.domain  }}
  postfix_hostname: {{ .Values.hostname |}}
  message_size_limit: {{ .Values.messageSizeLimit  }}
  postfix_relay: {{ .Values.postfixRelay }}
  postfix_relay_port: {{ .Values.postfixRelayPort  }}
  postfix_relay_network: {{ .Values.relayNetworks  }}
  relay_user: {{ .Values.relayUser }}
  relay_password: {{ .Values.relayPassword }}
