apiVersion: v1
kind: Secret
metadata:
  name: opendkim-keys-secret
  namespace: {{ .Values.NamespaceCluster }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mail.private: {{ .Values.opendkim_private_key | b64enc }}
  mail.txt: {{ .Values.opendkim_txt_record | b64enc }}
