apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: {{ .Values.NamespaceCluster }} 
  labels:
    app: nfs-server
spec:
  selector:
    app: nfs-server
  ports:
  - name: nfs-port
    port: 2049
    targetPort: 2049
    protocol: TCP
  - name: rpcbind-port
    port: 111
    targetPort: 111
    protocol: TCP
  type: ClusterIP  # Cambia a NodePort o LoadBalancer si es necesario
