apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres_name }}
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres_name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.postgres_name }}
          image: "{{ .Values.postgres_image }}:17"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.postgres_port }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql17/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: POSTGRES_DB

        - name: fluent-bit
          image: fluent/fluent-bit:2.1.8
          env:
            - name: FLUENT_ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: FLUENT_ELASTICSEARCH_USER
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: FLUENT_ELASTICSEARCH_PASSWORD
          volumeMounts:
            - name: postgres-logs
              mountPath: /var/log/postgresql

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgres_name }}-pv-claim
        - name: postgres-init
          configMap:
            name: postgres17-init-config
        - name: postgres-logs
          emptyDir: {}
