postgres_name: postgres
postgres_namespace: db-srv
replicaCount: 1
image:
  repository: postgres
  tag: 14
  pullPolicy: IfNotPresent
configMap:
  name: postgres-config
nodeRole: app
postgres_secrets_name: postgres-secrets
postgres_database: POSTFIXDB
postgres_user: postgresuser
postgres_password: "yourpassword"
postgres_host: postgres-host
postgres_port: 5432
