apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.qnodeapmname }}
  namespace: {{ .Values.qnodenamespace }}
  labels:
    app: {{ .Values.qnodapmname }}
spec:
  type: {{ .Values.databaseservicetype }}
  externalName: {{ .Values.apmserviceExternalName }}
  ports:
  - port: {{ .Values.apmport }}
    protocol: TCP
