# Default values for qnd100.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
qnodename: qnd031app
qnodenamespace: www-apps
ingress_name: qnd031-app-ingress
nodeRole: app

#Certificate

secret_name: smartquail-io-tls
qnd_commonName : smartquail.io
qnd_dns_names : meddes.smartquail.io
#Services
postgres_db : QND031STDB
qnodedatabasename: smartquaildb
databaseservicetype: ExternalName
databaseExternalName: smartquaildb.db-srv.svc.cluster.local
databaseport: 5432
#redis
#qnodecachename: redis
#cacheservicetype: ExternalName
#cacheExternalName: redis.cache.svc.cluster.local
#cacheport: 6379
#redis
qnodebrokername: rabbitmq
brokerservicetype: ExternalName
brokerExternalName: rabbitmq.brk-srv.svc.cluster.local
brokerport: 5672


qnodecachename: redis
cacheservicetype: ExternalName
cacheserviceExternalName: redis.cache-srv.svc.cluster.local
cacheport: 6379


image:
  repository: smartquail/qnd031app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


resources: 
   limits:
     cpu: 900m
     memory: 1Gi
   requests:
     cpu: 500m
     memory: 512Mi


