apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: smartquail-clusterissuer
spec:
  acme:
    email: phys.mauricio.silva@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name:  smartquail-io-secrets
    solvers:
    - http01:
        ingress:
          class: nginx