apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qnd41
spec:
  secretName: smartquail-tls-cert-secrets
  privateKey:
    rotationPolicy: Always
  commonName: qnd41.default.svc.cluster.local

  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - qnd41.default.svc.cluster.local
  usages:
   - digital signature
   - key encipherment
   - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer


