apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.fullname" . }}-service
  namespace: ai-models
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11434
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}