apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: auto-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000   # Permite al usuario 'node' escribir en el volumen
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            # === Autenticación básica ===
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: N8N_BASIC_AUTH_USER
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: N8N_BASIC_AUTH_PASSWORD

            # === Configuración general ===
            - name: WEBHOOK_URL
              value: "https://n8n.smartquail.io/"
            - name: N8N_HOST
              value: "n8n.smartquail.io"
            - name: N8N_PROTOCOL
              value: "https"
            - name: DJANGO_URL
              value: "http://qnd041app.www-apps.svc.cluster.local"

            # === Variables sensibles ===
            - name: WHATSAPP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: WHATSAPP_ACCESS_TOKEN
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: N8N_ENCRYPTION_KEY

            - name: DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_TYPE

            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_DATABASE

            - name: DB_POSTGRESDB_HOST
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_HOST

            - name: DB_POSTGRESDB_PORT
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_PORT

            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_USER

            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secrets
                  key: DB_POSTGRESDB_PASSWORD



          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n

      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
