apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
  namespace: mail-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfixadmin
  template:
    metadata:
      labels:
        app: postfixadmin
    spec:
      containers:
        - name: postfixadmin
          image: postfixadmin:3.3.15
          ports:
            - name: postfixadmin
              containerPort: 80
              protocol: TCP
          env:
            - name: POSTFIXADMIN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_DB_HOST
            - name: POSTFIXADMIN_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_DB_NAME
            - name: POSTFIXADMIN_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_DB_USER
            - name: POSTFIXADMIN_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_DB_PASSWORD
            - name: POSTFIXADMIN_DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_DB_TYPE
            - name: POSTFIXADMIN_SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_SMTP_SERVER
            - name: POSTFIXADMIN_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_SMTP_PORT
            - name: POSTFIXADMIN_ENCRYPT
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_ENCRYPT
            - name: POSTFIXADMIN_DKIM
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_DKIM
            - name: POSTFIXADMIN_DKIM_ALL_ADMINS
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: POSTFIXADMIN_DKIM_ALL_ADMINS


