apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postfixadmin-ingress
  namespace: db-srv 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/router.entrypoints: websecure
    nginx.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer  

spec:
  ingressClassName: nginx
  rules:
    - host: postfixadmin.smartquail.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postfixadmin-service
                port:
                  number: 80 
  tls:
    - secretName: postfixadmin-smartquail-io-tls
      hosts:
        - postfixadmin.smartquail.io