apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
  namespace: mail-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfixadmin
  template:
    metadata:
      labels:
        app: postfixadmin
    spec:
      containers:
        - name: postfixadmin
          image: postfixadmin:fpm-alpine
          ports:
            - containerPort: 8080
          env:
          - name: POSTFIXADMIN_DB_HOST
            valueFrom:
              secretKeyRef:
                name: postfixadmin-secrets
                key: POSTFIXADMIN_DB_HOST
          - name: POSTFIXADMIN_DB_NAME
            valueFrom:
              secretKeyRef:
                name: postfixadmin-secrets
                key: POSTFIXADMIN_DB_NAME
          - name: POSTFIXADMIN_DB_USER
            valueFrom:
              secretKeyRef:
                name: postfixadmin-secrets
                key: POSTFIXADMIN_DB_USER
          - name: POSTFIXADMIN_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postfixadmin-secrets
                key: POSTFIXADMIN_DB_PASSWORD
          - name: POSTFIXADMIN_DB_TYPE
            valueFrom:
              secretKeyRef:
                name: postfixadmin-secrets
                key: POSTFIXADMIN_DB_TYPE

