apiVersion: v1
kind: Service
metadata:
  name: postfixadmin-service
  namespace: mail-srv
  labels:
    app: postfixadmin
spec:
  type: ClusterIP
  selector:
    app: postfixadmin
  ports:
     - name: http
       port: 8080
       targetPort: 80
       protocol: TCP


       