apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: cert-manager 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: smartquail.dev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-api-key
              key: api-key
