apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  namespace: mail-microservers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      nodeSelector:
        role: mail  # Ajusta el selector según las etiquetas de tus nodos
      containers:
      - name: dovecot
        image: smartquail/qnd10dovecot:prod  # Ajusta la imagen según la versión que necesitas
        ports:
        - containerPort: 143  # IMAP
        - containerPort: 110  # POP3
        volumeMounts:
        - name: dovecot-config
          mountPath: /etc/dovecot
      volumes:
      - name: dovecot-config
        configMap:
          name: dovecot-config

  
