apiVersion: v1
kind: Service
metadata:
  name: dovecot-service
  namespace: {{ .Values.NameSpaceCluster }}
  labels:
    app: dovecot
spec:
  selector:
    app: dovecot  # Debe coincidir con las etiquetas del pod de Dovecot
  type: NodePort
  ports:
    - name: imap
      protocol: TCP
      port: 143          # IMAP sin cifrado
      targetPort: 143
      nodePort: 30143
    - name: imaps
      protocol: TCP
      port: 993          # IMAP con SSL/TLS
      targetPort: 993
      nodePort: 30993
    - name: pop3
      protocol: TCP
      port: 110          # POP3 sin cifrado
      targetPort: 110
      nodePort: 30110
    - name: pop3s
      protocol: TCP
      port: 995          # POP3 con SSL/TLS
      targetPort: 995
      nodePort: 30995

