apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  namespace: {{ .Values.NamespaceCluster }}
  labels:
    app: dovecot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
        - name: dovecot
          image: {{ .Values.dovecot_image }}  # Reemplaza con una imagen adecuada
          ports:
            - containerPort: 143 # Puerto IMAP
            - containerPort: 993 # Puerto IMAPS
          env:
          - name: DOMAIN
            valueFrom:
              secretKeyRef:
                name: dovecot-secrets
                key: DOMAIN
          - name: MAIL_LOCATION_PATH
            valueFrom:
              secretKeyRef:
                name: dovecot-secrets
                key: MAIL_LOCATION_PATH
          - name: POSTFIX_DB_HOST
            valueFrom:
              secretKeyRef:
                name: dovecot-secrets
                key: POSTFIX_DB_HOST 
          - name: POSTFIX_DB
            valueFrom:
              secretKeyRef:
                name: dovecot-secrets
                key: POSTFIX_DB 
          - name: POSTFIX_USER_DB
            valueFrom:
              secretKeyRef:
                name: dovecot-secrets
                key: POSTFIX_USER_DB
          - name: POSTFIX_PASSWORD_DB
            valueFrom:
              secretKeyRef:
                name: dovecot-secrets
                key: POSTFIX_PASSWORD_DB
          - name: MAIL_HOME_PATH
            valueFrom:
              secretKeyRef:
                name: dovecot-secrets
                key: MAIL_HOME_PATH    
          volumeMounts:
            - name: mail-certificates
              mountPath: /etc/dovecot/certs  # Certificados TLS
              readOnly: false
            - name: dovecot-mailbox
              mountPath: /var/mail  # Ruta para los buzones
            - name: dovecot-config
              mountPath: /etc/dovecot/conf.d/10-auth.conf
              subPath: 10-auth.conf
              readOnly: false
            - name: dovecot-config
              mountPath: /etc/dovecot/conf.d/10-mail.conf
              subPath: 10-mail.conf
              readOnly: false
            - name: dovecot-config
              mountPath: /etc/dovecot/conf.d/10-ssl.conf
              subPath: 10-ssl.conf
              readOnly: false
            - name: dovecot-config
              mountPath: /etc/dovecot/dovecot-sql.conf.ext
              subPath: dovecot-sql.conf.ext
              readOnly: false
            - name: dovecot-config
              mountPath: /etc/dovecot/auth-system.conf.ext
              subPath: auth-system.conf.ext 
              readOnly: false
            - name: dovecot-config
              mountPath: /etc/dovecot/dovecot.conf
              subPath: dovecot.conf
              readOnly: false
            - name: dovecot-postfix-socket
              mountPath: /var/spool/postfix/private  # Ruta compartida para el socket LMTP
      volumes:
        - name: dovecot-mailbox
          persistentVolumeClaim:
            claimName: dovecot-mailbox-pvc  # El PVC correspondiente al volumen
        - name: dovecot-config
          configMap:
            name: dovecot-config
        - name: mail-certificates
          projected:
            sources:
              - secret:
                  name: {{ .Values.tlsSecretName }}  # Usando la variable definida en values.yaml
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
            defaultMode: 0440
        - name: dovecot-postfix-socket
          emptyDir: {}  # Volumen temporal que Dovecot usará para crear el socket

