apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  namespace: {{ .Values.NamespaceCluster }}
  labels:
    app: dovecot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
        - name: dovecot
          image: {{ .Values.dovecot_image }}
          ports:
            - containerPort: 143   # Puerto IMAP
            - containerPort: 993   # Puerto IMAPS
            - containerPort: 995   # Puerto IMAPS
            - containerPort: 190   # Puerto IMAPS
            - containerPort: 8080   # Puerto IMAPS
            - containerPort: 9090   # Puerto IMAPS
            - containerPort: 110   # Puerto IMAPS
            - containerPort: 12345 # Puerto TCP para auth SASL (ajusta al puerto que uses)
            - containerPort: 24   # Puerto LMTP
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: dovecot-secrets
                  key: DOMAIN
            - name: MAIL_LOCATION_PATH
              valueFrom:
                secretKeyRef:
                  name: dovecot-secrets
                  key: MAIL_LOCATION_PATH
            - name: POSTFIX_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dovecot-secrets
                  key: POSTFIX_DB_HOST
            - name: POSTFIX_DB
              valueFrom:
                secretKeyRef:
                  name: dovecot-secrets
                  key: POSTFIX_DB
            - name: POSTFIX_USER_DB
              valueFrom:
                secretKeyRef:
                  name: dovecot-secrets
                  key: POSTFIX_USER_DB
            - name: POSTFIX_PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: dovecot-secrets
                  key: POSTFIX_PASSWORD_DB
            - name: MAIL_HOME_PATH
              valueFrom:
                secretKeyRef:
                  name: dovecot-secrets
                  key: MAIL_HOME_PATH
          volumeMounts:
            - name: imap-certificates
              mountPath: /etc/dovecot/ssl/
              readOnly: true
            - name: mailbox
              mountPath: /var/mail/
              readOnly: false

      volumes:
        - name: mailbox
          persistentVolumeClaim:
            claimName: mailbox-pvc
        - name: imap-certificates
          projected:
            sources:
              - secret:
                  name: {{ .Values.tlsSecretName }}
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
            defaultMode: 0440
