---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dovecot-mailbox
  # NOTA: Los PersistentVolumes son recursos a nivel cluster, no deben tener namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mail/
    type: DirectoryOrCreate
  # No storageClassName definido aquí
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-mailbox-pvc
  namespace: mail-srv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: dovecot-mailbox
  storageClassName: ""  # Indica explícitamente que no quieres storageClass
