---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dovecot-mailbox
  # Nota: Los PVs son recursos a nivel cluster, no uses "namespace" aquí
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain  # Para evitar que se borre si se elimina el PVC
  hostPath:
    path: /var/mail/
    type: DirectoryOrCreate
  # No se define storageClassName → Volumen estático
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-mailbox-pvc
  namespace: mail-srv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: dovecot-mailbox  # Enlaza explícitamente con el PV
