---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dovecot-mailbox
  # NOTA: Los PersistentVolumes son recursos a nivel cluster, no deben tener namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain  # Evita que se borre el PV si se elimina el PVC
  hostPath:
    path: /var/mail/
    type: DirectoryOrCreate
  # No definas storageClassName para un volumen estático que enlazas directamente con PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-mailbox-pvc
  namespace: mail-srv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: dovecot-mailbox  # Enlaza explícitamente con el PV "dovecot-mailbox"
  # No definas storageClassName aquí para que coincida con PV sin storageClass
