apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: {{ .Values.NameSpaceCluster }}
data:
  add_user.sh: |
    #!/bin/bash
    set -e

    # Función para registrar mensajes
    log() {
      echo "$(date +"%Y-%m-%d %H:%M:%S") - $1"
    }

    # Función para agregar un usuario
    addUserInfo() {
      local user_name="support"
      local user_domain="smartquail.io"
      local user_maildir="/var/mail/${user_domain}/${user_name}"

      # Verifica si el usuario ya existe en el sistema
      if ! id -u "$user_name" &>/dev/null; then
        log "Adding user '${user_name}'"

        # Añade el usuario como usuario de sistema (sin directorio home activo)
        adduser --system --home "/home/$user_name" --no-create-home "$user_name"

        # Crea el directorio Maildir para el usuario si no existe
        mkdir -p "${user_maildir}/"{tmp,new,cur}

        # Ajusta los permisos para el usuario de correo virtual
        chown -R vmail:vmail "${user_maildir}"
        chmod -R 700 "${user_maildir}"

        log "User '${user_name}' added with maildir '${user_maildir}'"
      else
        log "User '${user_name}' already exists"
      fi
    }

    # Llama a la función para agregar el usuario
    addUserInfo

    # Termina con un mensaje de éxito
    log "User setup script completed successfully"

  main.cf: |
    ###############
    # General
    ###############

    # Main domain and hostname
    mydomain = {{ DOMAIN }}
    myhostname = {{ HOSTNAME }}
    myorigin = $mydomain

    home_mailbox = Maildir/

    # Message size limit
    message_size_limit = {{ MESSAGE_SIZE_LIMIT }}

    # Relayed networks
    mynetworks = 127.0.0.0/8, [::1]/128, 172.18.0.0/16 ,64.233.160.0/19, 137.184.0.57/32, 66.102.0.0/20, 66.249.80.0/20, 72.14.192.0/18, 74.125.0.0/16, 108.177.0.0/17, 173.194.0.0/16, 209.85.128.0/17, 216.58.192.0/19, 35.190.0.0/17, {{ RELAYNETS }}

    inet_interfaces = all
    inet_protocols = ipv4

    virtual_transport = lmtp:unix:private/dovecot-lmtp

    transport_maps = pcre:/etc/postfix/transport.pcre

    # Empty alias list to override the configuration variable and disable NIS
    alias_maps = 

    # No destination restrictions
    mydestination = 

    # Relayhost if any is configured
    relayhost = [smtp.mail.smartquail.io]:587
    relay_domains = *

    ###############
    # Restrictions
    ###############

    # Delay all rejects until all information can be logged
    smtpd_delay_reject = no
    append_dot_mydomain = no

    # Helo restrictions are specified for smtp only in master.cf
    smtpd_helo_required = yes

    smtpd_sender_restrictions =
      permit_mynetworks,
      permit_sasl_authenticated,
      reject_non_fqdn_sender,
      reject_unknown_sender_domain,
      reject_unlisted_sender,
      reject_sender_login_mismatch,
      permit

    smtpd_recipient_restrictions =
      permit_mynetworks,
      permit_sasl_authenticated,
      reject_unauth_destination,
      permit

    smtpd_relay_restrictions =
      permit_mynetworks,
      permit_sasl_authenticated,
      reject_unauth_destination,

    smtpd_client_restrictions =
      permit_mynetworks,
      permit_sasl_authenticated,
      reject_unauth_destination

    smtpd_relay_before_recipient_restrictions = yes

    ###############
    # TLS Settings
    ###############

    smtp_tls_security_level = may
    smtpd_tls_security_level = may
    smtpd_tls_auth_only = no
    smtpd_tls_cert_file = /etc/ssl/certs/fullchain.pem
    smtpd_tls_key_file = /etc/ssl/private/privkey.pem
    smtpd_tls_received_header = yes
    smtp_tls_note_starttls_offer = yes
    smtpd_tls_loglevel = 1
    smtpd_tls_session_cache_timeout = 3600s

    tls_random_source = dev:/dev/urandom
    tlsmgr_cache_type = dovecot
    tls_session_cache_database = dovecot
    tls_session_cache_timeout = 1h
    tls_session_cache_size = 100000

    # Uncomment if using memcached for TLS session caching
    # tls_session_cache = memcached
    # tls_session_cache_memcached_server = memcached:11211
    # tls_session_cache_memcached_key = tls_cache

    smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1, TLSv1.2, TLSv1.3
    smtpd_tls_ciphers = high
    smtp_tls_loglevel = 1

    ###############
    # SASL Settings
    ###############

    smtpd_sasl_auth_enable = yes
    smtpd_sasl_type = dovecot
    smtpd_sasl_path = private/auth
    smtpd_sasl_authenticated_header = yes
    smtpd_sasl_security_options = noanonymous
    smtpd_sasl_tls_security_options = noanonymous
    smtpd_sasl_local_domain = $myhostname

    ###############
    # Extra Settings
    ###############

    maillog_file = /dev/stdout

    ##############
    # PostgreSQL configuration
    ###############

    virtual_mailbox_base = /var/mail

    # virtual_mailbox_domains = mail.smartquail.io
    virtual_mailbox_domains = pgsql:/etc/postfix/sql/virtual_mailbox_domains.cf
    virtual_mailbox_maps = pgsql:/etc/postfix/sql/virtual_mailbox_maps.cf
    virtual_alias_maps = pgsql:/etc/postfix/sql/virtual_alias_maps.cf

    virtual_uid_maps = static:1000
    virtual_gid_maps = static:1000
    virtual_alias_domains = *

  transport.pcre: |
    # /etc/postfix/transport
    # Enviar correos a gmail.com a través de Google SMTP servers
    /gmail\.com$/              smtp:[gmail-smtp-in.l.google.com]
    # Direcciones locales en {{ .Values.domain }}
    /{{ .Values.domain }}$/    :
    /^support@{{ .Values.domain }}$/ local:
    /@{{ .Values.domain }}$/     virtual

  master.cf: |
    # service type  private unpriv  chroot  wakeup  maxproc command + args
    #               (yes)   (yes)   (yes)   (never) (100)

    # Exposed SMTP services

    # Standard SMTP service for incoming mail
    smtp      inet  n       -       n       -       -       smtpd
      -o syslog_name=postfix/smtp
      -o smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination

    # Submission service for client mail submission (port 587)
    submission inet n       -       n       -       -       smtpd
      -o syslog_name=postfix/submission
      -o smtpd_sasl_auth_enable=yes
      -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination
      -o smtpd_tls_security_level=encrypt
      -o smtpd_tls_wrappermode=no
      -o smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3,TLSv1.2,TLSv1.3
      -o smtpd_tls_mandatory_ciphers=high

    # SMTPS service for secure SMTP (port 465)
    smtps     inet  n       -       n       -       -       smtpd
      -o syslog_name=postfix/smtps
      -o smtpd_tls_wrappermode=yes
      -o smtpd_sasl_auth_enable=yes
      -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination
      -o smtpd_tls_security_level=encrypt
      -o smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3,TLSv1.2,TLSv1.3
      -o smtpd_tls_mandatory_ciphers=high

    # Additional services
    outclean   unix n       -       n       -       0       cleanup
      -o header_checks=pcre:/etc/postfix/outclean_header_filter

    # Internal postfix services
    pickup    unix  n       -       n       60      1       pickup
    cleanup   unix  n       -       n       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       n       1000?   1       tlsmgr
    rewrite   unix  -       -       n       -       -       trivial-rewrite
    bounce    unix  -       -       n       -       0       bounce
    defer     unix  -       -       n       -       0       defer
    trace     unix  -       -       n       -       0       trace
    verify    unix  -       -       n       -       1       verify
    flush     unix  n       -       n       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       n       -       -       smtp
    error     unix  -       -       n       -       -       error
    retry     unix  -       -       n       -       -       error
    discard   unix  -       -       n       -       -       discard
    lmtp      unix  -       -       n       -       -       lmtp
    anvil     unix  -       -       n       -       1       anvil
    scache    unix  -       -       n       -       1       scache
    postlog   unix-dgram n  -       n       -       1       postlogd
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual

  sasl_passwd: |
    [smtp.{{ .Values.domain }}]:587    {{ .Values.saslUsername }}:{{ .Values.saslPassword }}

  virtual_mailbox_domains.cf: |
    user = ${POSTFIX_USER_DB}
    password = ${POSTFIX_PASSWORD_DB}
    dbname = ${POSTFIX_DB}
    hosts = ${POSTFIX_DB_HOST}

    # Query para obtener el dominio de un buzón de correo
    query = SELECT domain FROM virtual_domains WHERE domain='%s'

  virtual_alias_maps.cf: |
    user = ${POSTFIX_USER_DB}
    password = ${POSTFIX_PASSWORD_DB}
    dbname = ${POSTFIX_DB}
    hosts = ${POSTFIX_DB_HOST}

    # Query para obtener el destino de un alias
    query = SELECT destination FROM virtual_aliases WHERE source='%s'

  virtual_mailbox_maps.cf: |
    user = ${POSTFIX_USER_DB}
    password = ${POSTFIX_PASSWORD_DB}
    dbname = ${POSTFIX_DB}
    hosts = ${POSTFIX_DB_HOST}

    # Consulta para obtener la ruta del buzón de correo
    query = SELECT CONCAT('/var/mail/', domain, '/', email, '/Maildir/') FROM virtual_users, virtual_domains WHERE virtual_users.domain_id = virtual_domains.id AND email='%s'
