apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config
  namespace: {{ .Values.NameSpaceCluster }}
data:
  add_user.sh: |
    #!/bin/bash
    set -e

    # Función para registrar mensajes
    log() {
      echo "$(date +"%Y-%m-%d %H:%M:%S") - $1"
    }

    # Función para agregar un usuario
    addUserInfo() {
      local user_name="support"
      local user_domain="smartquail.io"
      local user_maildir="/var/mail/${user_domain}/${user_name}"

      # Verifica si el usuario ya existe en el sistema
      if ! id -u "$user_name" &>/dev/null; then
        log "Adding user '${user_name}'"

        # Añade el usuario como usuario de sistema (sin directorio home activo)
        adduser --system --home "/home/$user_name" --no-create-home "$user_name"

        # Crea el directorio Maildir para el usuario si no existe
        mkdir -p "${user_maildir}/"{tmp,new,cur}

        # Ajusta los permisos para el usuario de correo virtual
        chown -R vmail:vmail "${user_maildir}"
        chmod -R 700 "${user_maildir}"

        log "User '${user_name}' added with maildir '${user_maildir}'"
      else
        log "User '${user_name}' already exists"
      fi
    }

    # Llama a la función para agregar el usuario
    addUserInfo

    # Termina con un mensaje de éxito
    log "User setup script completed successfully"


  main.cf: |
    ###############
    # General
    ###############
    
    # Main domain and hostname
    mydomain = {{ .Values.domain }}
    myhostname = {{ .Values.hostname }}
    myorigin = $mydomain

    home_mailbox = {{ .Values.homeMailBox }}

    # Empty alias list to override the configuration variable and disable NIS
    alias_maps = 

    # Message size limit
    message_size_limit = {{ .Values.messageSizeLimit }}

    # Relayed networks
    mynetworks = 127.0.0.0/8, [::1]/128, 192.168.1.0/24, {{ .Values.relayNetworks }}

    mydestination = $myhostname, localhost.$mydomain, localhost

    inet_interfaces = all
    inet_protocols = all

    virtual_transport = lmtp:unix:private/dovecot-lmtp

    transport_maps = pcre:/etc/postfix/transport.pcre

    # Relayhost if any is configured
    relayhost = [smtp.mail.smartquail.io]:587

    relay_domains = 

    ###############
    # Restrictions
    ###############
    smtpd_delay_reject = no
    append_dot_mydomain = no
    smtpd_helo_required = yes

    smtpd_sender_restrictions =
        permit_mynetworks,                 
        permit_sasl_authenticated,         
        reject_non_fqdn_sender,            
        reject_unknown_sender_domain,     
        reject_unlisted_sender,            
        reject_sender_login_mismatch       

    smtpd_relay_restrictions =
        permit_mynetworks,                
        permit_sasl_authenticated,         
        reject_unauth_destination          

    smtpd_client_restrictions =

    smtpd_recipient_restrictions =
        permit_mynetworks,                 
        permit_sasl_authenticated,         
        reject_unauth_destination,         
        reject_non_fqdn_recipient,         
        reject_unknown_recipient_domain    

    smtpd_relay_before_recipient_restrictions = no

    ###############
    # TLS Settings
    ###############
    smtp_tls_security_level = may
    smtpd_tls_security_level = may
    smtpd_tls_auth_only = no
    smtpd_tls_cert_file = {{ .Values.postfixTlsCertFile }}
    smtpd_tls_key_file = {{ .Values.postfixTlsKeyFile }}
    smtpd_tls_received_header = yes
    smtp_tls_note_starttls_offer = yes
    smtpd_tls_loglevel = 1
    smtpd_tls_session_cache_timeout = 3600s
    tls_random_source = dev:/dev/urandom
    tlsmgr_cache_type = dovecot
    tls_session_cache_database = dovecot
    tls_session_cache_timeout = 1h
    tls_session_cache_size = 100000
    smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1, TLSv1.2, TLSv1.3
    smtpd_tls_ciphers = high
    smtp_tls_loglevel = 1

    ###############
    # SASL Settings
    ###############
    smtpd_sasl_auth_enable = yes
    smtpd_sasl_type = dovecot
    smtpd_sasl_path = unix:/var/spool/postfix/private/auth
    smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
    smtpd_sasl_authenticated_header = yes
    smtpd_sasl_security_options = noanonymous
    smtpd_sasl_tls_security_options = noanonymous
    smtpd_sasl_local_domain = $myhostname

    ###############
    # Extra Settings
    ###############
    maillog_file = /dev/stdout

    ##############
    # PostgreSQL configuration
    ###############
    virtual_mailbox_base = /var/mail
    virtual_mailbox_domains = pgsql:/etc/postfix/sql/virtual_mailbox_domains.cf
    virtual_mailbox_maps = pgsql:/etc/postfix/sql/virtual_mailbox_maps.cf
    virtual_alias_maps = pgsql:/etc/postfix/sql/virtual_alias_maps.cf
    virtual_minimum_uid = 100
    virtual_uid_maps = static:102
    virtual_gid_maps = static:102
    virtual_alias_domains = *

    milter_protocol = 6
    milter_default_action = accept
    smtpd_milters = unix:/var/spool/postfix/opendkim/opendkim.sock
    non_smtpd_milters = $smtpd_milters

  transport.pcre: |
    # /etc/postfix/transport
    # Enviar correos a gmail.com a través de Google SMTP servers
    /gmail\.com$/              smtp:[gmail-smtp-in.l.google.com]
    # Direcciones locales en {{ .Values.domain }}
    /{{ .Values.domain }}$/    :
    /^support@{{ .Values.domain }}$/ local:
    /@{{ .Values.domain }}$/     virtual

  master.cf: |
    # service type  private unpriv  chroot  wakeup  maxproc command + args
    #               (yes)   (yes)   (yes)   (never) (100)

    # Exposed SMTP services

    # Standard SMTP service for incoming mail
    smtp      inet  n       -       n       -       -       smtpd
      -o syslog_name=postfix/smtp
      -o smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination

    # Submission service for client mail submission (port 587)
    submission inet n       -       n       -       -       smtpd
      -o syslog_name=postfix/submission
      -o smtpd_sasl_auth_enable=yes
      -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination
      -o smtpd_tls_security_level=encrypt
      -o smtpd_tls_wrappermode=no
      -o smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3,TLSv1.2,TLSv1.3
      -o smtpd_tls_mandatory_ciphers=high

    # SMTPS service for secure SMTP (port 465)
    smtps     inet  n       -       n       -       -       smtpd
      -o syslog_name=postfix/smtps
      -o smtpd_tls_wrappermode=yes
      -o smtpd_sasl_auth_enable=yes
      -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_unauth_destination
      -o smtpd_tls_security_level=encrypt
      -o smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3,TLSv1.2,TLSv1.3
      -o smtpd_tls_mandatory_ciphers=high

    # Additional services
    outclean   unix n       -       n       -       0       cleanup
      -o header_checks=pcre:/etc/postfix/outclean_header_filter

    # Internal postfix services
    pickup    unix  n       -       n       60      1       pickup
    cleanup   unix  n       -       n       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       n       1000?   1       tlsmgr
    rewrite   unix  -       -       n       -       -       trivial-rewrite
    bounce    unix  -       -       n       -       0       bounce
    defer     unix  -       -       n       -       0       defer
    trace     unix  -       -       n       -       0       trace
    verify    unix  -       -       n       -       1       verify
    flush     unix  n       -       n       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    smtp      unix  -       -       n       -       -       smtp
    relay     unix  -       -       n       -       -       smtp
    error     unix  -       -       n       -       -       error
    retry     unix  -       -       n       -       -       error
    discard   unix  -       -       n       -       -       discard
    lmtp      unix  -       -       n       -       -       lmtp
    anvil     unix  -       -       n       -       1       anvil
    scache    unix  -       -       n       -       1       scache
    postlog   unix-dgram n  -       n       -       1       postlogd
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual

  sasl_passwd: |
    [smtp.{{ .Values.domain }}]:587    {{ .Values.saslUsername }}:{{ .Values.saslPassword }}

  virtual_mailbox_domains.cf: |
    user = ${POSTFIX_USER_DB}
    password = ${POSTFIX_PASSWORD_DB}
    dbname = ${POSTFIX_DB}
    hosts = ${POSTFIX_DB_HOST}

    # Query para obtener el dominio de un buzón de correo
    query = SELECT domain FROM virtual_domains WHERE domain='%s'

  virtual_alias_maps.cf: |
    user = {{ .Values.db_username }}
    password = {{ .Values.db_password }}
    dbname = {{ .Values.db_name }}
    hosts = {{ .Values.db_host }}

    # Query para obtener el destino de un alias
    query = SELECT destination FROM virtual_aliases WHERE source='%s'

  virtual_mailbox_maps.cf: |
    user = {{ .Values.db_username }}
    password = {{ .Values.db_password }}
    dbname = {{ .Values.db_name }}
    hosts = {{ .Values.db_host }}

    # Consulta para obtener la ruta del buzón de correo
    query = SELECT CONCAT('/var/mail/', domain, '/', email, '/Maildir/') FROM virtual_users, virtual_domains WHERE virtual_users.domain_id = virtual_domains.id AND email='%s'
