apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: postfix
  namespace: {{ .Values.NameSpaceCluster }}
  labels:
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postfix
    spec:
      serviceAccountName: postfix
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      securityContext:
        runAsUser: 0
        runAsGroup: 0

      containers:
        - name: postfix
          image: {{ .Values.postfiximage }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: 25
              hostPort: 25
            - name: smtps
              containerPort: 465
            - name: submission
              containerPort: 587
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: DOMAIN
            - name: HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: HOSTNAME
            - name: POSTFIX_USER_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_USER_DB
            - name: POSTFIX_PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_PASSWORD_DB
            - name: POSTFIX_IP
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_IP
            - name: POSTFIX_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB
            - name: POSTFIX_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB_HOST
            - name: POSTFIX_RELAY_USER
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_USER
            - name: POSTFIX_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PASSWORD
            - name: POSTFIX_RELAY
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY
            - name: POSTFIX_RELAY_PORT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PORT
            - name: RELAY_NETWORKS
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: RELAY_NETWORKS
            - name: MESSAGE_SIZE_LIMIT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MESSAGE_SIZE_LIMIT
            - name: MAIL_HOME_PATH
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MAIL_HOME_PATH
            - name: TLS_CERT_FILE
              value: /etc/ssl/tls.crt
            - name: TLS_KEY_FILE
              value: /etc/ssl/tls.key
            - name: SASL_TCP_HOST
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: SASL_TCP_HOST
            - name: SASL_TCP_PORT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: SASL_TCP_PORT

          livenessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 25
            initialDelaySeconds: 10
            periodSeconds: 60

          readinessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 25
            periodSeconds: 60

          resources:
            requests:
              cpu: "5m"
              memory: "16Mi"
            limits:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
                - NET_BIND_SERVICE

          volumeMounts:
            - name: mailbox
              mountPath: /var/mailbox
            - name: mail-certificates
              mountPath: /etc/ssl
              readOnly: true
            - name: postfix-config-volume
              mountPath: /etc/postfix/sql
              readOnly: true

      volumes:
        - name: mailbox
          persistentVolumeClaim:
            claimName: mailbox-pvc
        - name: mail-certificates
          projected:
            sources:
              - secret:
                  name: {{ .Values.tlsSecretName }}
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
        - name: postfix-config-volume
          configMap:
            name: postfix-config
