apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: postfix
  namespace: {{ .Values.NameSpaceCluster }}
  labels:
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postfix
    spec:
      serviceAccountName: postfix
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      securityContext:
        fsGroup: 1000  # Grupo que tendrá acceso a /var/mail

      # Eliminamos initContainer fix-permissions porque falla si el volumen no permite chown
      # En caso de que quieras volver a intentar, revisa el tipo de volumen y permisos en el host

      initContainers:
        - name: copy-postfix-config
          image: busybox
          command:
            - sh
            - -c
            - cp -r /postfix-config/* /postfix-config-writable/
          volumeMounts:
            - name: postfix-config-volume
              mountPath: /postfix-config
              readOnly: true
            - name: postfix-config-writable
              mountPath: /postfix-config-writable

      containers:
        - name: postfix
          image: {{ .Values.postfiximage }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: 25
              hostPort: 25
            - name: smtps
              containerPort: 465
            - name: submission
              containerPort: 587
          env:
            # Aquí van tus variables de entorno
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: DOMAIN
            # ... resto igual ...
            - name: TLS_CERT_FILE
              value: /etc/ssl/tls.crt
            - name: TLS_KEY_FILE
              value: /etc/ssl/tls.key

          livenessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 25
            initialDelaySeconds: 10
            periodSeconds: 60

          readinessProbe:
            failureThreshold: 2
            tcpSocket:
              port: 25
            periodSeconds: 60

          resources:
            requests:
              cpu: "5m"
              memory: "16Mi"
            limits:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            runAsUser: 0            # correr como root para evitar problemas de usuario inexistente
            runAsGroup: 0
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
                - NET_BIND_SERVICE

          volumeMounts:
            - name: dovecot-mailbox
              mountPath: /var/mail
            - name: mail-certificates
              mountPath: /etc/ssl
              readOnly: true
            - name: postfix-config-writable
              mountPath: /etc/postfix/sql
              readOnly: false

      volumes:
        - name: dovecot-mailbox
          persistentVolumeClaim:
            claimName: dovecot-mailbox-pvc
        - name: mail-certificates
          projected:
            sources:
              - secret:
                  name: {{ .Values.tlsSecretName }}
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
        - name: postfix-config-volume
          configMap:
            name: postfix-config
        - name: postfix-config-writable
          emptyDir: {}
