apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: {{ .Values.NameSpaceCluster }}
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
        - name: postfix
          image: {{ .Values.postfiximage }} # Imagen de Postfix con OpenDKIM incluido
          ports:
            - containerPort: 25
            - containerPort: 465
            - containerPort: 587
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: DOMAIN
            - name: HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: HOSTNAME
            - name: POSTFIX_USER_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_USER_DB
            - name: POSTFIX_PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_PASSWORD_DB
            - name: POSTFIX_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB
            - name: POSTFIX_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB_HOST        
            - name: POSTFIX_RELAY_USER
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_USER
            - name: POSTFIX_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PASSWORD
            - name: POSTFIX_RELAY
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY
            - name: POSTFIX_RELAY_PORT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PORT
            - name: RELAY_NETWORKS
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: RELAY_NETWORKS
            - name: MESSAGE_SIZE_LIMIT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MESSAGE_SIZE_LIMIT
            - name: MAIL_HOME_PATH
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MAIL_HOME_PATH
            - name: TLS_CERT_FILE
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: TLS_CERT_FILE
            - name: TLS_KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: TLS_KEY_FILE

            - name: DKIM_SOCKET
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: DKIM_SOCKET
          volumeMounts:
            - name: postfix-config
              mountPath: /etc/postfix/sql/virtual_mailbox_domains.cf
              subPath: virtual_mailbox_domains.cf
              readOnly: true
            - name: postfix-config
              mountPath: /etc/postfix/sql/virtual_alias_maps.cf
              subPath: virtual_alias_maps.cf
              readOnly: true
            - name: postfix-config
              mountPath: /etc/postfix/sql/virtual_mailbox_maps.cf
              subPath: virtual_mailbox_maps.cf
              readOnly: true
            - name: postfix-config
              mountPath: /etc/postfix/master.cf
              subPath: master.cf
              readOnly: true
            - name: postfix-config
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
              readOnly: false
      volumes:
        - name: postfix-config
          configMap:
            name: postfix-config
