---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailbox
spec:
  storageClassName: ""          # <-- Debe ser vacío para hostPath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mail
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailbox-pvc
  namespace: mail-srv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""          # <-- Debe coincidir exactamente con el PV (vacío)
  volumeName: mailbox