---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailbox
  # NOTA: Los PersistentVolumes son recursos a nivel cluster, no deben tener namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain  # Evita borrado accidental
  storageClassName: do-block-storage      # Aquí la clave: debe coincidir con PVC
  hostPath:
    path: /var/mail # Ruta en el nodo donde se almacenarán los datos
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailbox-pvc
  namespace: mail-srv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  volumeName: mailbox
