apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: {{ .Values.NamespaceCluster }}
  labels:
    app: postfix
spec:
  selector:
    app: postfix
  type: NodePort  # Acceso externo a través de puertos del nodo
  ports:
    - name: smtps
      protocol: TCP
      port: 465
      targetPort: 465
      nodePort: 32613   # Fijado: SMTPS
    - name: submission
      protocol: TCP
      port: 587
      targetPort: 587
      nodePort: 31193   # Fijado: Submission (STARTTLS)
