apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: {{ .Values.NamespaceCluster }}
  labels:
    app: postfix
spec:
  selector:
    app: postfix
  ports:
    - name: smtp
      protocol: TCP
      port: 25       # Puerto SMTP (recepción)
      targetPort: 25
    - name: smtps
      protocol: TCP
      port: 465      # Puerto SMTPS (envío seguro con SSL/TLS)
      targetPort: 465
    - name: submission
      protocol: TCP
      port: 587      # Puerto Submission (envío con STARTTLS)
      targetPort: 587
  type: LoadBalancer  # Cambia a ClusterIP si solo necesitas acceso interno
