apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: db-srv
  labels:
    app: elasticsearch
  type: ExternalName
  externalName: elasticsearch.logs-srv.svc.cluster.local
  ports:
  - port: 9200 
    protocol: TCP
