apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres_name }}
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_app_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres_app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres_app_name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.postgres_name }}
          image: "postgres:16.6"
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/pgdata
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d/
              name: postgres-config-volume
              readOnly: true
            - mountPath: /var/lib/postgresql/data/postgresql.conf
              name: postgres-config-volume
              subPath: postgresql-config
            - mountPath: /var/log/postgresql
              name: postgres-logs
          command: ["docker-entrypoint.sh", "postgres"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB

        - name: fluent-bit
          image: fluent/fluent-bit:2.1.8
          env:
            - name: FLUENT_ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: FLUENT_ELASTICSEARCH_USER
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: FLUENT_ELASTICSEARCH_PASSWORD
          volumeMounts:
            - name: postgres-logs
              mountPath: /var/log/postgresql
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
              readOnly: true

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgres_name }}-pv-claim

        - name: postgres-config-volume
          configMap:
            name: postgres-config

        - name: postgres-logs
          emptyDir: {}

        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
