apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Values.postgres_namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/postgresql/postgresql.log
        Tag           postgres.log
        DB            /var/log/flb_postgres.db
        Refresh_Interval 10
        Rotate_Wait   30
        Parser        json
        Mem_Buf_Limit 5MB

    [OUTPUT]
        Name              es
        Match             *
        Host              elasticsearch
        Port              9200
        Index             postgresql-logs
        Type              _doc
        Logstash_Format   On
        Logstash_Prefix   postgresql
        HTTP_User         ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd       ${FLUENT_ELASTICSEARCH_PASSWORD}
        tls               off

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S
        Time_Keep   On
