---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dovecot-mailbox
  namespace: {{ .Values.NamespaceCluster }}  # Seguir la convención de nombres
spec:
  capacity:
    storage: 5Gi  # Tamaño del volumen
  accessModes:
    - ReadWriteOnce  # Modificado para el acceso estándar
  storageClassName: standard  # Cambiado a una clase de almacenamiento estándar
  volumeMode: Filesystem  # Modo de volumen
  hostPath:
    path:  /var/mail  # Ruta en el nodo anfitrión donde se almacenará el volumen
    type: DirectoryOrCreate  # Crea el directorio si no existe

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-mailbox-pvc
  namespace: {{ .Values.NamespaceCluster }}
spec:
  accessModes:
    - ReadWriteOnce  # Mantiene coherencia con el PV
  resources:
    requests:
      storage: 5Gi  # Espacio solicitado para el volumen
  storageClassName: standard  # Clase de almacenamiento estándar
