apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.qnodebrokername }}
  namespace: {{ .Values.qnodenamespace }}
  labels:
    app: {{ .Values.qnodebrokername }}
spec:
  type: {{ .Values.brokerservicetype }}
  externalName: {{ .Values.brokerExternalName }}
  ports:
  - port: {{ .Values.brokerport }}
    protocol: TCP
