apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smartquail-cert
  namespace: www-apps
spec:
  secretName: smartquail-io-tls
  duration: 2160h # Duración del certificado en horas
  renewBefore: 360h # Renovar el certificado 360 horas antes de la expiración
  isCA: false
  keySize: 2048
  commonName: smartquail.io
  dnsNames:
    - smartquail.io
    - www.smartquail.io
  issuerRef:
    name: letsencrypt-cluster-issuer # Nombre del Issuer a utilizar
    kind: ClusterIssuer
