apiVersion: v1
kind: ConfigMap
metadata:
  name: qnd41-app-config
  namespace: {{ .Values.qnodenamespace }}
data:
  DEBUG: {{ .Values.Debug }}
  ALLOWED_HOSTS: {{ .Values.allowed_hosts }}
  DJANGO_SETTINGS_MODULE: {{ .Values.djangosettingsmodule }}
  WAGTAIL_SITE_NAME: {{ .Values.wagtailsitename }}
  WAGTAILADMIN_BASE_URL: {{ .Values.wagtailadminbaseurl  }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.djangosuperusername  }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.djangosuperuseremail  }}
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadminemail  }}
  PGADMIN_PASSWORD: {{ .Values.pgadminpassword  }}

  POSTGRES_DB: {{ .Values.qnodedatabasename}}
  POSTGRES_HOST: {{ .Values.qnodedatabasehost }}
  POSTGRES_USER : {{ .Values.qnodedatabaseusername }}
  POSTGRES_PASSWORD : {{ .Values.qnodedatabasepassword }}
  db_url: {{ .Values.databaseExternalName }}
   
  POSTGRES_ENGINE : {{ .Values.databaseengine }}
  POSTGRES_PORT : {{ .Values.databaseport }}
  LANG: {{ .Values.databaselang }}
  LC_COLLATE : {{ .Values.databaselscollate }}
  REDIS_HOST: {{ .Values.redishost }}
  REDIS_PORT: {{ .Values.redisport }}
  RABBITMQ_DEFAULT_USER : {{ .Values.rabbitmquser }}

  AWS_STORAGE_BUCKET_NAME: {{ .Values.awsstorebucketname }}
  AWS_S3_ENDPOINT_URL: {{ .Values.awss3endpointurl }}
  
  AWS_LOCATION: {{ .Values.awslocation }}
  STATICFILES_STORAGE: {{ .Values.staticfilesstorage }}
  MEDIA_STORAGE: {{ .Values.mediastorage }}

  BROKER_URL: {{ .Values.brokerurl }}
  RESULT_BACKEND: {{ .Values.resultbackend }}
  CELERY_RESULT_BACKEND: {{ .Values.celeryresultbackend }}
  CELERY_BROKER_URL: {{ .Values.celerybrokerurl }}

  EMAIL_HOST: {{ .Values.emailhost }}
  EMAIL_PORT: {{ .Values.emailport }}
  EMAIL_USE_TLS: {{ .Values.emailusetls }}
  EMAIL_HOST_USER: {{ .Values.emailhostuser }}
  DEFAULT_FROM_EMAIL: {{ .Values.defaultfromemail }}
  EMAIL_BACKEND: {{ .Values.emailbackend}}
  EMAIL_USE_SSL: {{ .Values.emailusessl }}



