postgres_name: postgres17
postgres_namespace: db-srv
postgres_image: postgres
postgres_app_name: postgres
postgres_secrets: postgres17-secrets
postgres_existing_volume_id: "f49c5738-8c14-11f0-a6dd-0a58ac120543" # Tu ID real de DigitalOcean
postgres_storage: "1Gi"
postgres_port : 5432
replicaCount: 1
nodeRole: app




