apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: postfix-hpa
  namespace: {{ .Values.NameSpaceCluster }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postfix  # Nombre del Deployment
  minReplicas: 1  # Número mínimo de réplicas
  maxReplicas: 2  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Escalar si el uso promedio de CPU excede el 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85  # Escalar si el uso promedio de memoria excede el 75%
