apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qnd41-pro-app-ingress
  namespace: qnd41-app
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: www.smartquail.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.qnodename }}
                port:
                  number: 80


