apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qnd41-pro-app-ingress
  namespace: qnd41-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: "app.juansilvaphoto.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: qnd41-pro
            port:
              number: 80