apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qnd41-pro-app-ingress
  namespace: {{ .Values.qnodenamespace }}
  annotations:
    ingressClassName: nginx
    cert-manager.io/issuer: "letsencrypt-stage"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - smartquail.smartquail.io
    secretName: smartquail-io-tls
  rules:
  - host: smartquail.smartquail.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.qnodename }}
            port:
              number: 80

nodeSelector:
  pool: nginx-ingress




