apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qnd41-pro-app-ingress
  namespace: {{ .Values.qnodenamespace }}
  annotations:
    ingressClassName: nginx
    cert-manager.io/issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.smartquail.io
    secretName: letsencrypt-staging-ttl
  rules:
  - host: app.smartquail.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.qnodename }}
            port:
              number: 80






