apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-digitalocean-issuer
spec:
  acme:
    email: smartquail.info@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: clusterissuretoken  # Nombre del Secret que contiene la API Key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: clusterissuretoken  # El Secret que contiene el token
            key: digitalocean_api_key  # La clave dentro del Secret donde está el token
