apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qnd41-pro-app-ingress
  namespace: qnd41-app
spec:
  ingressClassName: nginx-ingress
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qnd41-pro 
            port:
              number: 80