apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.qnodename }}
  namespace: {{ .Values.qnodenamespace }}
  labels:
    app: {{ .Values.qnodename }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.qnodename }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.qnodename }}
    spec:
      securityContext:
        fsGroup: 1000  #  Ubicado correctamente en nivel de Pod
      containers:
        - name: {{ .Values.qnodename }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 9000  #  Puerto corregido
              protocol: TCP
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/qnd041app/
            - name: uwsgi-logs
              mountPath: /var/log/uwsgi/
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: PORT
              value: "9000"
            #  Django & App Environment
            - name: DJANGO_LOG_FILE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_LOG_FILE
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_SETTINGS_MODULE
            - name: ROOT_URLCONF
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: ROOT_URLCONF
            - name: WSGI_APPLICATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: WSGI_APPLICATION
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: ALLOWED_HOSTS
            - name: DJANGO_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_ENV
            - name: DJANGO_STATE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_STATE
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DEBUG
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_SUPERUSER_USERNAME
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_SUPERUSER_PASSWORD
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_SUPERUSER_EMAIL
            - name: DJANGO_SUPERUSER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DJANGO_SUPERUSER_KEY
            #  Infra
            - name: IP
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: IP
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DOMAIN
            - name: HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: HOSTNAME
            #  PostgreSQL
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: POSTGRES_PORT
            - name: POSTGRES_ENGINE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: POSTGRES_ENGINE
            #  Redis & RabbitMQ
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: REDIS_PASSWORD
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: RABBITMQ_DEFAULT_PASS
            #  AWS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: AWS_STORAGE_BUCKET_NAME
            - name: AWS_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: AWS_S3_ENDPOINT_URL
            - name: AWS_LOCATION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: AWS_LOCATION
            #  Celery
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: CELERY_BROKER_URL
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: CELERY_RESULT_BACKEND
            - name: CELERY_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: CELERY_TIMEZONE
            #  Email
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: EMAIL_BACKEND
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: EMAIL_PORT
            - name: EMAIL_USE_TLS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: EMAIL_USE_TLS
            - name: EMAIL_USE_SSL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: EMAIL_USE_SSL
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: EMAIL_HOST_USER
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: EMAIL_HOST_PASSWORD
            - name: DEFAULT_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: DEFAULT_FROM_EMAIL
            #  WhatsApp
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_WHATSAPP_FROM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: TWILIO_WHATSAPP_FROM
            #  Otros
            - name: LANG
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: LANG
            - name: LC_COLLATE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: LC_COLLATE
            - name: SOCIAL_AUTH_FACEBOOK_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: SOCIAL_AUTH_FACEBOOK_KEY
            - name: SOCIAL_AUTH_FACEBOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: SOCIAL_AUTH_FACEBOOK_SECRET
            - name: SOCIAL_AUTH_FACEBOOK_SCOPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: SOCIAL_AUTH_FACEBOOK_SCOPE
            - name: SOCIAL_AUTH_TWITTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: SOCIAL_AUTH_TWITTER_KEY
            - name: SOCIAL_AUTH_TWITTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: SOCIAL_AUTH_TWITTER_SECRET
            - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
            - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
            - name: GA_KEY_CONTENT_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: GA_KEY_CONTENT_ENV
            - name: GA_VIEW_ID_ENV
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: GA_VIEW_ID_ENV
            - name: BRAINTREE_M_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: BRAINTREE_M_ID
            - name: BRAINTREE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: BRAINTREE_KEY
            - name: BRAINTREE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: BRAINTREE_PRIVATE_KEY

        - name: fluent-bit
          image: fluent/fluent-bit:2.1.8
          securityContext:
            runAsUser: 0
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: FLUENT_ELASTICSEARCH_HOST
            - name: FLUENT_ELASTICSEARCH_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: FLUENT_ELASTICSEARCH_PORT
            - name: FLUENT_ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: FLUENT_ELASTICSEARCH_USER
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.qnodename }}-app-secrets
                  key: FLUENT_ELASTICSEARCH_PASSWORD
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/qnd041app
            - name: uwsgi-logs
              mountPath: /var/log/uwsgi
            - name: fluent-bit-config-qnd041app
              mountPath: /fluent-bit/etc/
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: uwsgi-logs
          emptyDir: {}
        - name: fluent-bit-config-qnd041app
          configMap:
            name: fluent-bit-config-qnd041app
