apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meddes-smartquail-io-tls
  namespace: www-apps
spec:
  secretName: meddes-smartquail-io-tls
  duration: 2160h # Duración del certificado en horas
  renewBefore: 360h # Renovar el certificado 360 horas antes de la expiración
  isCA: false
  commonName: qnd03101.smartquail.io
  dnsNames:
    - qnd03101.smartquail.io
    - smartquail.io  # Agregar smartquail.io como dnsName adicional
  issuerRef:
    name: letsencrypt-cluster-issuer # Nombre del Issuer a utilizar
    kind: ClusterIssuer
