apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Values.qnodenamespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush            5
        Daemon           Off
        Log_Level        info
        Parsers_File     parsers.conf

    [INPUT]
        Name             tail
        Path             /var/log/qnd031app/qnd031app.log
        Tag              app.django
        DB               /var/log/qnd031app/qnd031app.db
        Parser           docker
        Refresh_Interval 5

    [INPUT]
        Name             tail
        Path             /var/log/uwsgi/uwsgi.log
        Tag              app.uwsgi
        DB               /var/log/uwsgi/uwsgi.db
        Parser           uwsgi
        Refresh_Interval 5

    [OUTPUT]
        Name             es
        Match            app.django
        Host             elasticsearch
        Port             9200
        Index            django-logs
        Replace_Dots     On
        Retry_Limit      False
        HTTP_User        ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd      ${FLUENT_ELASTICSEARCH_PASSWORD}


    [OUTPUT]
        Name             es
        Match            app.uwsgi
        Host             elasticsearch
        Port             9200
        Index            uwsgi-logs
        Replace_Dots     On
        Retry_Limit      False
        HTTP_User        ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd      ${FLUENT_ELASTICSEARCH_PASSWORD}


  parsers.conf: |
    [PARSER]
        Name             docker
        Format           json
        Time_Key         time
        Time_Format      %Y-%m-%dT%H:%M:%S.%L
        Time_Keep        On

    [PARSER]
        Name             uwsgi
        Format           regex
        Regex            ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?<level>[A-Z]+) (?<message>.*)
        Time_Key         time
        Time_Format      %Y-%m-%d %H:%M:%S
        Multiline        On
        Multiline_Firstline ^\d{4}-\d{2}-\d{2}
        Multiline_Nextline  ^\s|^Traceback|^\s+File
        Time_Keep        On
