apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smartquail-certificate
  namespace: qnd41-app
spec:
  secretName: smartquail-io-secrets
  issuerRef:
    name: ssl-issuer
    kind: Issuer
  dnsNames:
    - smartquail.io