apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.name }}
  namespace: {{ .Values.postgresql.namespace }}
  labels:
    app: {{ .Values.postgresql.name }}
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgresql.name }}
  template:
    metadata:
      namespace: {{ .Values.postgresql.namespace }}
      labels:
        app: {{ .Values.postgresql.name }}
    spec:
      nodeSelector:
        role: {{ .Values.postgresql.nodeRole }}  # Añadido nodeSelector
      restartPolicy: Always
      containers:
        - name: {{ .Values.postgresql.name }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.postgresql.name }}
          envFrom:
            - configMapRef:
                name: {{ .Values.postgresql.configMap.name }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.secrets.name }}
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: {{ .Values.postgresql.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.name }}-pv-claim
