apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres_name }}
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres_name }} # Corregido para que coincida con los labels
  template:
    metadata:
      labels:
        app: {{ .Values.postgres_name }}
    spec:
      nodeSelector:
        role: {{ .Values.nodeRole | default "app" }} # Valor por defecto para evitar fallos
      restartPolicy: Always
      containers:
       - name: {{ .Values.postgres_name }}
         image: "postgres:15.10-alpine3.20"
         imagePullPolicy: {{ .Values.postgres_image_pullPolicy | default 'IfNotPresent' }}

          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d/
              name: init-scripts
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name | default "postgres-config" }} # Valor por defecto
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets_name | default "postgres-secrets" }} # Valor por defecto
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name | default "postgres-config" }} # Valor por defecto
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name | default "postgres-config" }} # Valor por defecto
                  key: POSTGRES_USER
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgres_name }}-pv-claim
        - name: init-scripts
          configMap:
            name: {{ .Values.configMap.name | default "postgres-config" }} # Valor por defecto
