apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres_name }}
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres_name }}
  template:
    metadata:
      namespace: {{ .Values.postgres_namespace }}
      labels:
        app: {{ .Values.postgres_name }}
    spec:
      nodeSelector:
        role: {{ .Values.nodeRole }}  # Añadido nodeSelector
      restartPolicy: Always
      containers:
        - name: {{ .Values.postgres_name }}
          image: "{{ .Values.postgres_image }}:{{ .Values.postgres_tag_image }}"
          imagePullPolicy: {{ .Values.postgres_image_pullPolicy }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.postgres_name }}
            - mountPath: /docker-entrypoint-initdb.d/
              name: init-scripts
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets_name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_USER
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: {{ .Values.postgres_name }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres_name }}-pv-claim
        - name: init-scripts
          configMap:
            name: {{ .Values.configMap.name }}
