apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: db-srv
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@smartquail.io"  # Cambia esto a tu correo deseado
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "Ms95355672@"    # Cambia esto por una contraseña segura