apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres_name }}-pv-volume
  namespace: {{ .Values.postgres_namespace }}
  labels:
    type: local
    app: {{ .Values.postgres_name }}
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce  # Usamos ReadWriteOnce para volúmenes locales (cuidado si se va a compartir entre múltiples pods)
  persistentVolumeReclaimPolicy: Retain  # Esto asegura que el volumen no se elimine accidentalmente
  hostPath:
    path: "/mnt/data"  # Asegúrate de que esta ruta exista en el nodo donde se va a montar el volumen
    type: DirectoryOrCreate  # Esto garantiza que el directorio sea creado si no existe

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres_name }}-pv-claim
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce  # Debe coincidir con el PersistentVolume, por lo que se usa ReadWriteOnce aquí también
  resources:
    requests:
      storage: 500Mi
