apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  rabbitmq.conf: |
    # Configuración personalizada de RabbitMQ (si es necesario)
    # Ejemplo:
    loopback_users.guest = false
