apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres_name }}-pv-volume
  namespace: {{ .Values.postgres_namespace }}
  labels:
    type: local
    app: {{ .Values.postgres_name }}
spec:
  storageClassName: standard
  capacity:
    storage: {{ .Values.postgres_storage | default "500Mi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/{{ .Values.postgres_name }}/data"  # Directorio independiente
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres_name }}-pv-claim
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_name }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres_storage | default "500Mi" }}
