apiVersion: v1
kind: Secret
metadata:
  namespace: qnd41-app
  name: qnd41-do-dns
data:
  access-token: ZG9wX3YxX2FmNWUzYWJkM2NmYjU5MWY1ZTc0NGUyOGE2MDUzZDdmYTI3ZTk1OTM2MjdiM2Q0MTU0ZDU3YTJhZDY3MzRlMDA=
  

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-qnd41-issuer
spec:
  acme:
    email: smartquail.info@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: qnd41-do-dns
    solvers:
      - selector: {}
        dns01:
          digitalocean:
            tokenSecretRef:
              name: qnd41-do-dns
              key: access-token