# Default values for qnd100.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
qnodename: qnd41-pro
qnodenamespace: qnd41-app
nodeRole: app

#Services
qnodedatabasename: smartquaildb
databaseservicetype: ExternalName
databaseExternalName: smartquaildb.postgres.svc.cluster.local
databaseport: 5432
#redis
qnodecachename: redis
cacheservicetype: ExternalName
cacheExternalName: redis.cache.svc.cluster.local
cacheport: 6379
#redis
qnodebrokername: rabbitmq
brokerservicetype: ExternalName
brokerExternalName: rabbitmq.brokers.svc.cluster.local
brokerport: 5672

image:
  repository: smartquail/qnd41app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


resources: 
   limits:
     cpu: 50m
     memory: 128Mi
   requests:
     cpu: 25m
     memory: 64Mi


