apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
  namespace: mail-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfixadmin
  template:
    metadata:
      labels:
        app: postfixadmin
    spec:
      containers:
        - name: postfixadmin
          image: postfixadmin:fpm-alpine
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "{{ .Values.db_host }}"  # Dirección de tu servicio MySQL
            - name: DB_NAME
              value: "{{ .Values.db_name }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfixadmin-secrets
                  key: db_password
          volumeMounts:
            - name: config-volume
              mountPath: /etc/postfixadmin
      volumes:
        - name: config-volume
          configMap:
            name: postfixadmin-config
