apiVersion: v1
kind: ConfigMap
metadata:
  name: postfixadmin-config
  namespace: mail-srv
data:
  config.inc.php: |
    <?php
    // Configuration for PostfixAdmin
    $CONF['database_host'] = 'mysql-service.mail.svc.cluster.local';
    $CONF['database_user'] = 'admin';
    $CONF['database_password'] = 'password';
    $CONF['database_name'] = 'postfixadmin';
