apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: db-srv 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/router.entrypoints: websecure
    nginx.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer  

spec:
  ingressClassName: nginx
  rules:
    - host: pgadmin.smartquail.io 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 80 
  tls:
    - secretName: pgadmin-cert
      hosts:
        - pgadmin.smartquail.io 
