apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: db-srv
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: PGADMIN_DEFAULT_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/pgadmin  # Montaje en el directorio correcto
              name: pgadmin-data  # Volumen persistente para datos
          securityContext:
            runAsUser: 5050  # Asegúrate de usar el UID del contenedor (por ejemplo 5050, que es típico de pgAdmin)
            runAsGroup: 5050  # El mismo GID para asegurar consistencia
            fsGroup: 5050  # Esto asegura que los archivos del volumen sean accesibles para el grupo
            supplementalGroups:
              - 5050  # Puedes agregar más grupos según sea necesario
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc  # Usando el PVC definido anteriormente
