apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: db-srv
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
        - name: init-pgadmin-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/pgadmin/sessions && \
              chown -R 5050:5050 /var/lib/pgadmin
          volumeMounts:
            - name: shared-pg-data
              mountPath: /var/lib/pgadmin
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: PGADMIN_DEFAULT_PASSWORD
          volumeMounts:
            - name: shared-pg-data
              mountPath: /var/lib/pgadmin
              subPath: pgadmin
            - name: shared-pg-data
              mountPath: /backups
              readOnly: true

          securityContext:
            runAsUser: 5050
            runAsGroup: 5050
            fsGroup: 5050
      volumes:
        - name: shared-pg-data
          persistentVolumeClaim:
            claimName: postgres17-pv-claim
