---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data
  namespace:  db-srv
spec:
  capacity:
    storage: 200Mi  # Tamaño del volumen
  accessModes:
    - ReadWriteOnce  # Modificado para el acceso estándar
  storageClassName: standard  # Cambiado a una clase de almacenamiento estándar
  volumeMode: Filesystem  # Modo de volumen
  hostPath:
    path:  /var/lib/pgadmin  # Ruta en el nodo anfitrión donde se almacenará el volumen
    type: DirectoryOrCreate  # Crea el directorio si no existe

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: db-srv
spec:
  accessModes:
    - ReadWriteOnce  # Mantiene coherencia con el PV
  resources:
    requests:
      storage: 200Mi  # Espacio solicitado para el volumen
  storageClassName: standard  # Clase de almacenamiento estándar