apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: brk-srv
data:
  rabbitmq.conf: |
    ## Configuración de los logs ##
    log.dir = /var/log/rabbitmq
    log.file = rabbit@rabbitmq.log
    log.console.level = info

    ## Configuración del plugin de management (puerto de UI) ##
    management.listener.port = 15672

    ## Configuración de las colas (ver nota abajo) ##
    queue_master_locator = min-masters

    ## Otras configuraciones útiles ##
    listeners.tcp.default = 5672
    listeners.ssl.default = 5671
    default_vhost = /
    default_user = ${RABBITMQ_DEFAULT_USER}
    default_pass = ${RABBITMQ_DEFAULT_PASS}
