apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: brk-srv
data:
  fluent.conf: |
    <source>
      @type tail
      tag rabbitmq.*
      path /var/log/rabbitmq/*.log
      format none
      read_from_head true
    </source>

    <match rabbitmq.**>
      @type elasticsearch
      host "#{ENV['FLUENTD_ELASTICSEARCH_HOST']}"
      port 9200
      logstash_format true
      flush_interval 10s
      user "#{ENV['FLUENTD_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENTD_ELASTICSEARCH_PASS']}"
    </match>
