apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: brk-srv
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/rabbitmq/*.log
        Tag               rabbitmq.*
        Refresh_Interval  5
        Rotate_Wait       30
        DB                /tmp/rabbitmq.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [FILTER]
        Name      grep
        Match     rabbitmq.*
        Regex     log    .*

    [OUTPUT]
        Name          es
        Match         rabbitmq.*
        Host          ${ELASTICSEARCH_HOST}
        Port          9200
        HTTP_User     ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd   ${FLUENT_ELASTICSEARCH_PASSWORD}
        Index         rabbitmq-logs


  parsers.conf: |
    [PARSER]
        Name   rabbitmq
        Format regex
        Regex  ^(?<time>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3} GMT) \\[(?<pid>\\d+)\\] (?<level>[A-Z]+):(?<message>.*)
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S.%L GMT
