apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: brk-srv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Puede ser Delete o Retain según tus necesidades
  storageClassName: standard  # Si estás utilizando almacenamiento dinámico, ajusta este nombre
  hostPath:  # Solo para pruebas en un nodo específico
    path: "/mnt/data/rabbitmq"  # Asegúrate de que esta ruta exista en tu nodo