apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # <-- Match explícito sin usar StorageClass
  hostPath:
    path: "/mnt/data/rabbitmq"  # Asegúrate de que existe en el nodo
