apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: brk-srv
type: Opaque
data:
  rabbitmq_user: {{ .Values.rabbitmq_user | b64enc }}  # Codificar en base64
  rabbitmq_password: {{ .Values.rabbitmq_passwd | b64enc }}  # Codificar en base64

