apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-config
  namespace: mail-micro-servers
data:
  dovecot.conf: |
    # Dovecot configuration
    protocols = imap pop3
    mail_location = maildir:~/Maildir
    auth_mechanisms = plain login
  10-ssl.conf: |
    ssl_cert = </etc/dovecot/private/dovecot.pem
    ssl_key = </etc/dovecot/private/dovecot.key
