apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendkim
  labels:
    app: opendkim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendkim
  template:
    metadata:
      labels:
        app: opendkim
    spec:
      containers:
      - name: opendkim
        image: smartquail/qndopendkim100:latest
        ports:
        - containerPort: 8891
          name: milter
        volumeMounts:
        - name: opendkim-keys
          mountPath: /etc/opendkim/keys  # Montamos el PVC aquí
      volumes:
      - name: opendkim-keys
        persistentVolumeClaim:
          claimName: opendkim-keys-pvc  # Usamos el PVC aquí
