apiVersion: v1
kind: Service
metadata:
  name: dovecot
  namespace: mail-micro-servers
spec:
  ports:
  - port: 143
    targetPort: 143
    protocol: TCP
    name: imap
  - port: 110
    targetPort: 110
    protocol: TCP
    name: pop3
  selector:
    app: dovecot
