#Creamos el configMap para configurar las opciones de NGINX, es decir Headers, tiempos de respuesta etc... 
---
apiVersion: v1
data:
  allow-snippet-annotations: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx
data: 
   
  


 
 
   
    