apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres_name }}
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_app_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres_app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres_app_name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.postgres_name }}
          image: "postgres:17"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.postgres_port | default 5432 }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true
            - name: postgres-logs
              mountPath: /var/log/postgresql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: POSTGRES_DB

        - name: fluent-bit
          image: fluent/fluent-bit:2.1.8
          env:
            - name: FLUENT_ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: FLUENT_ELASTICSEARCH_USER
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets }}
                  key: FLUENT_ELASTICSEARCH_PASSWORD
          volumeMounts:
            - name: postgres-logs
              mountPath: /var/log/postgresql
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
              readOnly: true

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgres_name }}-pv-claim

        - name: postgres-init
          configMap:
            name: {{ .Values.postgres_init_configmap }}

        - name: postgres-logs
          emptyDir: {}

        - name: fluent-bit-config
          configMap:
            name: {{ .Values.fluent_bit_configmap }}
