apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres_name }}
  namespace: {{ .Values.postgres_namespace }}
  labels:
    app: {{ .Values.postgres_name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres_name }}
  template:
    metadata:
      namespace: {{ .Values.postgres_namespace }}
      labels:
        app: {{ .Values.postgres_name }}
    spec:
      nodeSelector:
        role: {{ .Values.nodeRole }}  # Añadido nodeSelector
      restartPolicy: Always
      containers:
        - name: "smartquaildb"
          image: {{ .Values.postgres_image }}:{{ .Values.postgres_tag_image }}
          imagePullPolicy: {{ .Values.postgres_image_pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres_port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.postgres_name }}
          envFrom:
            - configMapRef:
                name: {{ .Values.postgres_name }}-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres_secrets_name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.postgres_database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres_user }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: {{ .Values.postgres_name }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres_name }}-pv-claim
