apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.name }}-service
  namespace: {{ .Values.postgresql.namespace }}
spec:
  selector:
    app: {{ .Values.postgresql.name }}
  ports:
    - protocol: TCP
      port: 5432  # Puerto en el servicio
      targetPort: 5432  # Puerto en el contenedor
  clusterIP: None  # Esto se puede modificar según las necesidades de acceso
