apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres_name }}-service
  namespace: {{ .Values.postgres_namespace }}
spec:
  selector:
    app: {{ .Values.postgres_name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres_port }}  # Puerto en el servicio
      targetPort: {{ .Values.postgres_port }}  # Puerto en el contenedor
  type: {{ .Values.postgres_service_type }}
