apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: digitalocean-issuer
spec:
  digitalocean:
    apiKeySecretRef:
      name: {{ .Values.apiKeySecretRef.name }}
      key: {{ .Values.apiKeySecretRef.key }}
