apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.qnodename }}
  namespace: {{ .Values.qnodenamespace }}
  labels:
    app: {{ .Values.qnodename }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.qnodename }}
  template:
    metadata:
      namespace: {{ .Values.qnodenamespace }}
      labels:
        app: {{ .Values.qnodename }}
    spec:
      nodeSelector:
        role: {{ .Values.nodeRole }}  # Añadido nodeSelector
      restartPolicy: Always
      containers:
        - name: {{ .Values.qnodename }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data -E es_EC.UTF-8
              name: {{ .Values.qnodename }}
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD 
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: {{ .Values.qnodename }}
          persistentVolumeClaim:
            claimName: {{ .Values.qnodename }}-pv-claim
