apiVersion: v1
kind: Secret
metadata:
  name: smartquail-io-secrets
  namespace: qnd41-app
type: Opaque
stringData:
   API Key: 
   api-key: 'gHzS2Br3JXoi_GDbthUVnshe8gcgLw5Tv6p'
  # - or -
  # Token:
  # api-token: your-api-token