apiVersion: v1
kind: ConfigMap
metadata:
  name: qnd11-app-config
  namespace: {{ .Values.qnodenamespace }}
data:
  POSTGRES_DB: {{ .Values.qnodedbname}}
  POSTGRES_HOST: {{ .Values.qnodedbservername}}
  db_url: {{ .Values.databaseExternalName}}