replicaCount: 1
qnodename: qnd10-pro
qnode_type: qnd10-app
qnodenamespace: qnd10-app
hostname: businessapp.smartquail.io
businessname: businessapp
qnodedbname: QND41STGDB
qnodedbservername: smartquaildb
databaseservicetype: ExternalName
databaseExternalName: smartquaildb.postgres.svc.cluster.local
databaseport: 5432

image:
  repository: smartquail/qnd10app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

resources: 
   limits:
     cpu: 100m
     memory: 512Mi
   requests:
     cpu: 50m
     memory: 256Mi