apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-pv
  namespace: postfix
spec:
  capacity:
    storage: 2Gi  # Ajusta según tus necesidades
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  # Asegúrate de que esta clase de almacenamiento existe en tu clúster
  hostPath:
    path: /var/mail  # Ruta en el nodo del host para el almacenamiento
