apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-certificates
  namespace: mail-microservers
spec:
  secretName: mail-smartquail-io-tls
  duration: 2160h # Duración del certificado en horas
  renewBefore: 360h # Renovar el certificado 360 horas antes de la expiración
  isCA: false
  keySize: 2048
  commonName: mail-smartquail.io
  dnsNames:
    - mail.smartquail.io
  issuerRef:
    name: letsencrypt-staging # Nombre del Issuer a utilizar
    kind: ClusterIssuer
