apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: mail-microservers
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      nodeSelector:
        role: app # Etiqueta del nodo para Postfix
      containers:
      - name: postfix
        image: boky/postfix:edge-alpine # Reemplaza con la imagen real de Postfix
        ports:
        - containerPort: 25
        env:
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: postfix_domain

        - name: HOSTNAME
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: postfix_hostname

        - name: POSTFIX_RELAY_USER
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: relay_user
        - name: POSTFIX_RELAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: relay_password

        - name: POSTFIX_RELAY
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: postfix_relay

        - name: POSTFIX_RELAY_PORT
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: postfix_relay_port

        - name: RELAY_NETWORKS
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: postfix_relay_network

        - name: MESSAGE_SIZE_LIMIT
          valueFrom:
            secretKeyRef:
              name: postfix-secrets
              key: message_size_limit 

        - name: POSTFIX_TLS_CERT_FILE
          value: /etc/postfix/certs/tls.crt
          
        - name: POSTFIX_TLS_KEY_FILE
          value: /etc/postfix/certs/tls.key

        volumeMounts:
        - name: mail-certs
          mountPath: /etc/postfix/certs
          readOnly: true

        - name: postfix-config
          mountPath: /etc/postfix/

        - name: postfix-dovecot-socket
          mountPath: /var/spool/postfix/private
          
        - name: postfix-mailbox
          mountPath: /var/mail

      volumes:
      - name: mail-certs
        projected:
          sources:
          - secret:
              name: mailpost-certificates  # Certificado gestionado por CertManager
              items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key

      - name: postfix-config
        configMap:
          name: postfix-config  

      - name: postfix-dovecot-socket
        persistentVolumeClaim:
          claimName: postfix-dovecot-socket-pvc

      - name: postfix-mailbox
        persistentVolumeClaim:
          claimName: postfix-mailbox-pv