apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: {{ .Values.NameSpaceCluster }}
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: postfix
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
          image: {{ .Values.postfiximage }}
          ports:
            - containerPort: 25      # Puerto interno del contenedor
              name: smtp
            - containerPort: 465
              name: smtps
            - containerPort: 587
              name: submission
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: DOMAIN
            - name: HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: HOSTNAME
            - name: TLS_CERT_FILE
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: TLS_CERT_FILE
            - name: TLS_KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: TLS_KEY_FILE
            - name: MAIL_POSTFIX_HOME_PATH
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MAIL_POSTFIX_HOME_PATH
            - name: POSTFIX_IP
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_IP
            - name: POSTFIX_USER_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_USER_DB
            - name: POSTFIX_PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_PASSWORD_DB
            - name: POSTFIX_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB
            - name: POSTFIX_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB_HOST
            - name: POSTFIX_RELAY_USER
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_USER
            - name: POSTFIX_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PASSWORD
            - name: POSTFIX_RELAY
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY
            - name: POSTFIX_RELAY_PORT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PORT
            - name: MESSAGE_SIZE_LIMIT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MESSAGE_SIZE_LIMIT
            - name: MAILBOX_SIZE_LIMIT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MAILBOX_SIZE_LIMIT
          volumeMounts:
            - name: mail-certificates
              mountPath: /etc/ssl/
              readOnly: true
            - name: mailbox
              mountPath: /var/mail/
              readOnly: false
            - name: dkim-keys
              mountPath: /etc/opendkim/keys
              readOnly: true
      volumes:
        - name: mail-certificates
          projected:
            sources:
              - secret:
                  name: {{ .Values.tlsSecretName }}
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
        - name: mailbox
          persistentVolumeClaim:
            claimName: mailbox-pvc
        - name: postfix-config
          configMap:
            name: postfix-config
        - name: dkim-keys
          secret:
            secretName: opendkim-keys
            defaultMode: 0400

