apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: {{ .Values.NameSpaceCluster }}
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
        - name: postfix
          image: {{ .Values.postfiximage }}  # Imagen de Postfix con OpenDKIM incluido
          ports:
            - containerPort: 25
            - containerPort: 465
            - containerPort: 587
          env:
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: DOMAIN
            - name: HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: HOSTNAME
            - name: TLS_CERT_FILE
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: TLS_CERT_FILE
            - name: TLS_KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: TLS_KEY_FILE
            - name: MAIL_POSTFIX_HOME_PATH
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MAIL_POSTFIX_HOME_PATH
            - name: POSTFIX_IP
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_IP
            - name: POSTFIX_USER_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_USER_DB
            - name: POSTFIX_PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_PASSWORD_DB
            - name: POSTFIX_DB
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB
            - name: POSTFIX_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_DB_HOST
            - name: POSTFIX_RELAY_USER
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_USER
            - name: POSTFIX_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PASSWORD
            - name: POSTFIX_RELAY
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY
            - name: POSTFIX_RELAY_PORT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: POSTFIX_RELAY_PORT
            - name: MESSAGE_SIZE_LIMIT
              valueFrom:
                secretKeyRef:
                  name: postfix-secrets
                  key: MESSAGE_SIZE_LIMIT
          volumeMounts:
            - name: dovecot-postfix-socket
              mountPath: /var/spool/dovecot/private   # Monta el socket de Dovecot en la ubicación correcta
            - name: mail-certificates
              mountPath: /etc/ssl/  # Monta el volumen de certificados en /etc/ssl/
              readOnly: true  # Solo lectura
            - name: postfix-config
              mountPath: /etc/postfix/sql/virtual_alias_maps.cf
              subPath: virtual_alias_maps.cf
              readOnly: true
            - name: postfix-config
              mountPath: /etc/postfix/sql/virtual_mailbox_domains.cf
              subPath: virtual_mailbox_domains.cf
              readOnly: true
            - name: postfix-config
              mountPath: /etc/postfix/sql/virtual_mailbox_maps.cf
              subPath: virtual_mailbox_maps.cf
              readOnly: true
      volumes:
        - name: mail-certificates
          projected:
            sources:
              - secret:
                  name: {{ .Values.tlsSecretName }}
                  items:
                    - key: tls.crt
                      path: tls.crt
                    - key: tls.key
                      path: tls.key
        - name: dovecot-postfix-socket
          persistentVolumeClaim:
            claimName: dovecot-postfix-socket-pvc
        - name: dovecot-mailbox
          persistentVolumeClaim:
            claimName: dovecot-mailbox-pvc
        - name: postfix-config
          configMap:
            name: postfix-config
