apiVersion: v1
kind: PersistentVolume
metadata:
  name: dovecot-mailbox
  namespace: mail-microservers
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany  # Varios pods pueden acceder al mismo volumen a la vez
  storageClassName: manual
  volumeMode: Filesystem
  nfs:
    path: /nfsshare  # Ruta compartida en el servidor NFS
    server: nfs-server.mail-microservers.svc.cluster.local  # Servicio NFS en el clúster
