apiVersion: v1
kind: PersistentVolume
metadata:
  name: postfix-mailbox-pv
  namespace: mail-microservers
spec:
  capacity:
    storage: 5Gi  # Ajusta según tus necesidades
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  # Asegúrate de que esta clase de almacenamiento existe en tu clúster
  hostPath:
    path: /var/mail  # Ruta en el nodo del host para el almacenamiento
