
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-pvc
  namespace: postfix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Debe ser igual o menor que la capacidad del PersistentVolume
  storageClassName: manual  # Debe coincidir con el `storageClassName` del PersistentVolume
