apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postfix-dovecot-socket-pvc
  namespace: mail-microservers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi  # Espacio suficiente para el socket
  storageClassName: manual  # Debe coincidir con el `storageClassName` del PersistentVolume
