---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailbox
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # explícitamente vacío para evitar conflictos
  hostPath:
    path: /var/mail
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailbox-pvc
  namespace: mail-srv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""        # Debe coincidir con el PV (vacío)
  volumeName: mailbox         # Se enlaza directamente al PV manual
