apiVersion: v1
kind: Secret
metadata:
  name: postfix-secrets
  namespace: mail-microservers
type: Opaque
data:
  postfix_domain: c21hcnRxdWFpbC5pbw==
  postfix_hostname: bWFpbC5zbWFydHF1YWlsLmlv
  message_size_limit : NTAwMDAwMDA=
  postfix_relay: c210cC5tYWlsLnNtYXJ0cXVhaWwuaW8=
  postfix_relay_port: NTg3
  postfix_relay_network: NjQuMTguMC4wLzIwLCA2NC4yMzMuMTYwLjAvMTksIDY2LjEwMi4wLjAvMjAsIDY2LjI0OS44MC4wLzIwLCA3Mi4xNC4xOTIuMC8xOCwgNzQuMTI1LjAuMC8xNiwgMTA4LjE3Ny4wLjAvMTcsIDE3My4xOTQuMC4wLzE2LCAyMDkuODUuMTI4LjAvMTcsIDIxNi41OC4xOTIuMC8xOSwgMzUuMTkwLjAuMC8xNw==
  relay_user: c3VwcG9ydEBzbWFydHF1YWlsLmlv
  relay_password: TXM5NTM1NTY3MkA= 
  