apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: {{ .Values.NamespaceCluster }}
  labels:
    app: postfix
spec:
  selector:
    app: postfix
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 30025  # Puerto asignado en cada nodo
    - protocol: TCP
      port: 465
      targetPort: 465
      nodePort: 30465  # Puerto asignado en cada nodo
    - protocol: TCP
      port: 587
      targetPort: 587
      nodePort: 30587  # Puerto asignado en cada nodo
  type: NodePort
