apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: {{ .Values.NamespaceCluster }}  # Asegúrate de tener esta variable correctamente en values.yaml
  labels:
    app: postfix
spec:
  type: NodePort
  selector:
    app: postfix
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 31225  # Este será el puerto al que se redirige el tráfico externo desde el nodo (vía iptables)
    - name: smtps
      protocol: TCP
      port: 465
      targetPort: 465
      nodePort: 30465  # Dentro del rango NodePort (30000-32767)
    - name: submission
      protocol: TCP
      port: 587
      targetPort: 587
      nodePort: 30587  # Dentro del rango NodePort
