apiVersion: v1
kind: Service
metadata:
  name: postfix-service
  namespace: postfix
  labels:
    app: postfix
spec:
  selector:
    app: postfix
  ports:
  - protocol: TCP
    port: 25       # Puerto para SMTP
    targetPort: 25 # Puerto en el contenedor para SMTP
  - protocol: TCP
    port: 465      # Puerto para SMTPS
    targetPort: 465 # Puerto en el contenedor para SMTPS
  - protocol: TCP
    port: 587      # Puerto para Submission
    targetPort: 587 # Puerto en el contenedor para Submission
  type: LoadBalancer  # Cambiar a LoadBalancer si necesitas exponerlo externamente