apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.qnodecachename }}
  namespace: {{ .Values.qnodenamespace }}
  labels:
    app: {{ .Values.qnodecachename }}
spec:
  type: {{ .Values.cacheservicetype }}
  externalName: {{ .Values.cacheserviceExternalName }}
  ports:
  - port: {{ .Values.cacheport }}
    protocol: TCP
