apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.qnodedatabasename }}
  namespace: {{ .Values.qnodenamespace }}
  labels:
    app: {{ .Values.qnodedatabasename }}
spec:
  type: {{ .Values.databaseservicetype }}
  externalName: {{ .Values.databaseExternalName }}
  ports:
  - port: {{ .Values.databaseport }}
    protocol: TCP
