apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qnd41-tls-certificate
  namespace: qnd41-app
spec:
  secretName: smartquail-io-tls
  duration: 2160h
  renewBefore: 360h
  isCA: false
  commonName: smartquail.io
  dnsNames:
    - smartquail.io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
