apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: qnd41-app
spec:
  acme:
    email: phys.mauricio.silva@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-ttl
    solvers:
    - http01:
        ingress:
          class: nginx


